version: "3"
services:
  minecraft-server:
    image: openjdk:8-jre
    container_name: minecraft-server-1.20.1
    working_dir: /minecraft
    volumes:
      - .:/minecraft
    command: ["sh run.sh"]
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      - EULA="TRUE"
